// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Statement = 3,
  Keyword = 4,
  Identifier = 5,
  Number = 6,
  String = 7,
  Char = 8,
  Attribute = 9,
  Operator = 10,
  Punctuation = 11
